# C++中断继续 goto 语句

> 原文:[https://codescracker.com/cpp/cpp-jump-statements.htm](https://codescracker.com/cpp/cpp-jump-statements.htm)

jump (break、continue、goto 和 return)语句无条件地在函数内转移程序控制。C++有四个执行无条件分支的语句:

*   返回
*   转到
*   破裂
*   继续

其中，你可以在程序的任何地方使用 return 和 goto，而 break 和 continue 用在最小的闭包里，比如循环等等。除了以上四个，C++还提供了一个标准的库函数 exit()来帮助你跳出程序。

return 语句用于从函数返回。现在我们来详细讨论一下。

## C++ goto 语句

goto 语句可以将程序控制转移到程序中的任何地方。goto 语句的目标由标签标记。目标标签和 goto 必须出现在同一个函数中。

下面是 C++中 goto 语句的语法:

```
goto label;
:
label :
```

其中标签是用户提供的标识符，可以出现在 goto 之前或之后。例如，下面的代码片段:

```
a = 0 ;
start :
cout << "\n" << ++a ;
if(a < 50)
   goto start ;
```

打印数字从 1 到 50。cout 打印++a 的值，然后如果检查 a 是否小于 50，则控制转移到标签 start 否则，控制将转移到 if 后面的语句。

标签不能紧接在右大括号之前。例如，下面的代码片段是错误的:

```
:
{
   goto last :
   :
   last :       //wrong ! A label is preceding the closing brace }.
}
```

要处理此约束，可以在标签后使用 null 语句，如下所示:

```
:
{
   goto last :
   :
   last : ;      //correct now
}
```

**提示** -如果一个标签刚好出现在右大括号之前，那么这个标签后面必须有一个空语句。

## C++ break 语句

break 语句使程序能够跳过部分代码。break 语句终止最小的封闭 while、do-while、for 或 switch 语句。执行从紧跟在被终止的语句体后面的语句处继续。

以下代码片段为您提供了一个 break 语句的示例:

```
int a, b, c, i;
for(i=0; i<20; i++)
{
   cout << "Enter 2 numbers" ;
   cin >> a >> b ;
   if(b == 0)
      break;
   else
      c = a/b ;
   cout << "\n Quotient =" << c << "\n" ;
   :
```

上面的代码片段输入了两个数字。如果数字 b 为零，循环立即终止，否则重复输入数字并显示它们的商。

如果 break 语句出现在嵌套循环结构中，那么它只会导致从它出现的那个循环中退出。例如:

```
:
for(i=0; i<10; i++)
{
   j=0;
   cout << "\n Enter character";
   cin >> ch;
   cout << "\n";
   for( ; ; )
   {
      cout << ch;
      j++ ;
      if(j == 10)
         break;
   }
   cout << "\n...." ;
}
```

上面的代码片段输入一个字符并打印 10 次。内部循环有一个无限循环结构，但是一旦 j 变成 10，break 语句就终止它，控制转到内部循环后面的语句，该语句打印一行破折号。

switch 语句中使用的 break 只会影响该开关，也就是说，它只会终止它出现的那个开关。它不会影响交换机所在的任何环路。

## C++ continue 语句

continue 是另一个类似 break 语句的跳转语句，因为这两个语句都跳过了代码的一部分。但是 continue 语句与 break 有些不同。它不是强制终止，而是强制进行循环的下一次迭代，跳过其间的任何代码。

对于 For 循环，continue 通过更新变量导致下一次迭代，然后导致测试表达式的求值。对于 while 和 do-while 循环，程序控制传递给条件测试。

**注意**-continue 语句跳过其余的循环语句，并导致循环的下一次迭代。

以下代码片段为您提供了一个 continue 语句的示例:

```
:
int a, b, c, i;
for(i=0; i<20; i++)
{
   cout << "\n Enter 2 numbers" ;
   cin >> a >> b ;
   if(b == 0)
   {
      cout << "\n The denominator cannot be zero" << "Enter again !";
      continue;
   }
   else
      c = a/b ;
   cout << "\n Quotient =" << c << "\n" ;
}
```

有时您需要过早地放弃循环迭代。break 和 continue 语句都有帮助，但是在不同的情况下。

**提示** -不要混淆 break(退出程序块)和 continue(退出剩余语句)语句。

循环中的 break 语句将中止循环，并将控制权转移给循环后面的语句。continue 语句将放弃当前迭代，让循环开始下一次迭代。

## C++中断并继续语句示例

下面的示例程序使用两个循环来执行相同的操作，但是用 continue 替换了 break 语句。先看一段代码，然后看输出，以理解 break 和 continue 语句之间的区别:

```
/* C++ Jump Statements - C++ break and continue Statement */

#include<iostream.h>
#include<conio.h>
void main()
{
   clrscr();
   cout<<"The loop with \'break\' produces output as:\n";
   for(int i=1; i<=10; i++)
   {
      if((i%3)==0)
         break;
      else
         cout<<i<<endl;
   }
   cout<<"\nThe loop with \'continue\' produce output as:\n";
   for(i=1; i<=10; i++)
   {
      if((i%3)==0)
         continue;
      else
         cout<<i<<endl;
   }
   getch();
}
```

当编译和执行 C++程序时，它将产生以下输出:

![c++ jump statement](../Images/f3d669a5a14c27881f71b9f863ccfec0.png)

## C++ exit()函数

就像您可以使用 break 语句来中断循环一样，您也可以使用 C++的库函数 exit()来中断程序。这个函数使程序一遇到就终止，不管它出现在程序列表的什么地方。下面的程序说明了 exit()函数的使用:

```
/* C++ Jump Statements - C++ exit() Function */

#include<iostream.h>
#include<conio.h>
#include<process.h>
void main()
{
   clrscr();
   int num, i;
   cout<<"Enter the number: ";
   cin>>num;
   for(i=2; i<=num/2; i++)
   {
      if(num%i==0)
      {
         cout<<"\nNot a prime number.. !!";
         getch();
         exit(0);
      }
   }
   cout<<"\nIt is a prime number.";
   getch();
}
```

当编译并执行上述 C++程序时，它将产生以下输出:

![c++ break statement](../Images/b53b4288d7e1a8b4489a75ea5c356cea.png)
![c++ continue statement](../Images/bcd7cbaa8f7ba688e256ac91330f0400.png)

上面的程序接受一个数，并测试它是否是质数。如果这个数能被 2 到 1/2 之间的任何数整除，程序会提示这个数不是质数，并退出程序，因为这是由 exit()函数引起的。

exit()函数本身没有任何返回值。它的参数，在上面的程序中是 0，被返回给操作系统。这个值可以在批处理文件中测试，其中 ERROR LEVEL 为您提供 exit()函数提供的返回值。通常，值 0 表示成功终止，任何其他数字表示有错误。

exit()函数已在头文件 process.h 下定义，该头文件必须包含在使用 exit()函数的程序中。

[C++在线测试](/exam/showtest.php?subid=3)

* * *

* * *